/**
 * Badge Seed Data - Initial 30+ badges for the achievement system
 * Run this script to populate the badges table with initial badge definitions
 */

import type { NewBadge } from '@/lib/db/schema';

export const INITIAL_BADGES: NewBadge[] = [
  // ==================== VOLUME BADGES ====================
  {
    id: 'first_trade',
    name: 'The Beginning',
    description: 'Your trading journey starts here',
    category: 'VOLUME',
    tier: 'BRONZE',
    icon: '🎯',
    requirement: JSON.stringify({ type: 'TOTAL_TRADES', value: 1 }),
    points: 5,
    order: 1,
    isActive: true,
  },
  {
    id: 'hundred_club',
    name: 'Century',
    description: 'Reached 100 recorded trades',
    category: 'VOLUME',
    tier: 'BRONZE',
    icon: '📊',
    requirement: JSON.stringify({ type: 'TOTAL_TRADES', value: 100 }),
    points: 50,
    order: 2,
    isActive: true,
  },
  {
    id: 'five_hundred',
    name: 'Rising Star',
    description: '500 trades tracked',
    category: 'VOLUME',
    tier: 'SILVER',
    icon: '🚀',
    requirement: JSON.stringify({ type: 'TOTAL_TRADES', value: 500 }),
    points: 100,
    order: 3,
    isActive: true,
  },
  {
    id: 'thousand_trades',
    name: 'Diamond Trader',
    description: '1,000 trades milestone',
    category: 'VOLUME',
    tier: 'GOLD',
    icon: '💎',
    requirement: JSON.stringify({ type: 'TOTAL_TRADES', value: 1000 }),
    points: 200,
    order: 4,
    isActive: true,
  },
  {
    id: 'five_thousand',
    name: 'Elite Trader',
    description: 'Elite 5k trades club',
    category: 'VOLUME',
    tier: 'PLATINUM',
    icon: '🏆',
    requirement: JSON.stringify({ type: 'TOTAL_TRADES', value: 5000 }),
    points: 500,
    order: 5,
    isActive: true,
  },

  // ==================== WIN STREAK BADGES ====================
  {
    id: 'hot_streak',
    name: 'On Fire',
    description: 'Three days of profits',
    category: 'STREAK',
    tier: 'BRONZE',
    icon: '🔥',
    requirement: JSON.stringify({ type: 'WIN_STREAK', value: 3 }),
    points: 30,
    order: 1,
    isActive: true,
  },
  {
    id: 'lightning_week',
    name: 'Electric',
    description: 'Five days winning streak',
    category: 'STREAK',
    tier: 'SILVER',
    icon: '⚡',
    requirement: JSON.stringify({ type: 'WIN_STREAK', value: 5 }),
    points: 50,
    order: 2,
    isActive: true,
  },
  {
    id: 'perfect_week',
    name: 'Flawless',
    description: 'One full week of wins',
    category: 'STREAK',
    tier: 'GOLD',
    icon: '🌟',
    requirement: JSON.stringify({ type: 'WIN_STREAK', value: 7 }),
    points: 100,
    order: 3,
    isActive: true,
  },
  {
    id: 'kings_streak',
    name: 'Unstoppable',
    description: 'Ten day winning streak',
    category: 'STREAK',
    tier: 'GOLD',
    icon: '👑',
    requirement: JSON.stringify({ type: 'WIN_STREAK', value: 10 }),
    points: 150,
    order: 4,
    isActive: true,
  },
  {
    id: 'eagle_streak',
    name: 'Legendary',
    description: 'Legendary 15-day streak',
    category: 'STREAK',
    tier: 'PLATINUM',
    icon: '🦅',
    requirement: JSON.stringify({ type: 'WIN_STREAK', value: 15 }),
    points: 250,
    order: 5,
    isActive: true,
  },

  // ==================== PROFITABILITY BADGES ====================
  {
    id: 'first_profit',
    name: 'In the Money',
    description: 'Your first green day',
    category: 'PROFIT',
    tier: 'BRONZE',
    icon: '💰',
    requirement: JSON.stringify({ type: 'PROFIT_TOTAL', value: 1 }),
    points: 10,
    order: 1,
    isActive: true,
  },
  {
    id: 'profit_milestone',
    name: 'Money Maker',
    description: '$1k profit milestone',
    category: 'PROFIT',
    tier: 'BRONZE',
    icon: '💵',
    requirement: JSON.stringify({ type: 'PROFIT_TOTAL', value: 1000 }),
    points: 75,
    order: 2,
    isActive: true,
  },
  {
    id: 'big_earner',
    name: 'Big League',
    description: '$5k profit achieved',
    category: 'PROFIT',
    tier: 'SILVER',
    icon: '💸',
    requirement: JSON.stringify({ type: 'PROFIT_TOTAL', value: 5000 }),
    points: 150,
    order: 3,
    isActive: true,
  },
  {
    id: 'profit_master',
    name: 'Gold Standard',
    description: '$10k profit milestone',
    category: 'PROFIT',
    tier: 'GOLD',
    icon: '🏅',
    requirement: JSON.stringify({ type: 'PROFIT_TOTAL', value: 10000 }),
    points: 250,
    order: 4,
    isActive: true,
  },
  {
    id: 'diamond_hands',
    name: 'Diamond League',
    description: '$25k profit achieved',
    category: 'PROFIT',
    tier: 'PLATINUM',
    icon: '💎',
    requirement: JSON.stringify({ type: 'PROFIT_TOTAL', value: 25000 }),
    points: 500,
    order: 5,
    isActive: true,
  },

  // ==================== CONSISTENCY BADGES ====================
  {
    id: 'daily_logger',
    name: 'Committed',
    description: 'Logged trades 7 days straight',
    category: 'CONSISTENCY',
    tier: 'BRONZE',
    icon: '📝',
    requirement: JSON.stringify({ type: 'LOG_STREAK', value: 7 }),
    points: 40,
    order: 1,
    isActive: true,
  },
  {
    id: 'monthly_warrior',
    name: 'Dedicated',
    description: 'Full month of logging',
    category: 'CONSISTENCY',
    tier: 'SILVER',
    icon: '📅',
    requirement: JSON.stringify({ type: 'LOG_STREAK', value: 30 }),
    points: 100,
    order: 2,
    isActive: true,
  },
  {
    id: 'quarterly_champion',
    name: 'Disciplined',
    description: '60 days logged in quarter',
    category: 'CONSISTENCY',
    tier: 'GOLD',
    icon: '🎖️',
    requirement: JSON.stringify({ type: 'TOTAL_LOGGING_DAYS', value: 60, minPeriod: 90 }),
    points: 200,
    order: 3,
    isActive: true,
  },
  {
    id: 'annual_legend',
    name: 'Unstoppable',
    description: '200 days logged in year',
    category: 'CONSISTENCY',
    tier: 'PLATINUM',
    icon: '🏛️',
    requirement: JSON.stringify({ type: 'TOTAL_LOGGING_DAYS', value: 200 }),
    points: 400,
    order: 4,
    isActive: true,
  },

  // ==================== SOP COMPLIANCE BADGES ====================
  {
    id: 'sop_starter',
    name: 'By the Book',
    description: '20 consecutive SOP-compliant trades',
    category: 'SOP',
    tier: 'BRONZE',
    icon: '✅',
    requirement: JSON.stringify({ type: 'SOP_STREAK', value: 20 }),
    points: 40,
    order: 1,
    isActive: true,
  },
  {
    id: 'sop_master',
    name: 'Rule Follower',
    description: '90%+ SOP compliance',
    category: 'SOP',
    tier: 'SILVER',
    icon: '📖',
    requirement: JSON.stringify({ type: 'SOP_RATE', value: 90, minTrades: 100 }),
    points: 100,
    order: 2,
    isActive: true,
  },
  {
    id: 'perfect_discipline',
    name: 'Flawless Execution',
    description: '50 consecutive SOP-compliant trades',
    category: 'SOP',
    tier: 'GOLD',
    icon: '🎓',
    requirement: JSON.stringify({ type: 'SOP_STREAK', value: 50 }),
    points: 150,
    order: 3,
    isActive: true,
  },
  {
    id: 'sop_legend',
    name: 'The Disciplined One',
    description: 'Elite SOP compliance - 95%+ over 500 trades',
    category: 'SOP',
    tier: 'PLATINUM',
    icon: '🏆',
    requirement: JSON.stringify({ type: 'SOP_RATE', value: 95, minTrades: 500 }),
    points: 300,
    order: 4,
    isActive: true,
  },

  // ==================== PERFORMANCE BADGES ====================
  {
    id: 'sharpshooter',
    name: 'Accurate',
    description: 'Achieve 70%+ win rate over minimum 50 trades',
    category: 'PERFORMANCE',
    tier: 'BRONZE',
    icon: '🎯',
    requirement: JSON.stringify({ type: 'WIN_RATE', value: 70, minTrades: 50 }),
    points: 60,
    order: 1,
    isActive: true,
  },
  {
    id: 'sniper',
    name: 'Precision',
    description: 'Maintain 75%+ win rate over minimum 100 trades',
    category: 'PERFORMANCE',
    tier: 'SILVER',
    icon: '🔫',
    requirement: JSON.stringify({ type: 'WIN_RATE', value: 75, minTrades: 100 }),
    points: 120,
    order: 2,
    isActive: true,
  },
  {
    id: 'elite_performer',
    name: 'Top Tier',
    description: 'Achieve elite 80%+ win rate over minimum 100 trades',
    category: 'PERFORMANCE',
    tier: 'GOLD',
    icon: '🎖️',
    requirement: JSON.stringify({ type: 'WIN_RATE', value: 80, minTrades: 100 }),
    points: 200,
    order: 3,
    isActive: true,
  },
  {
    id: 'win_rate_king',
    name: 'Untouchable',
    description: 'Master level: 85%+ win rate over minimum 200 trades',
    category: 'PERFORMANCE',
    tier: 'PLATINUM',
    icon: '👑',
    requirement: JSON.stringify({ type: 'WIN_RATE', value: 85, minTrades: 200 }),
    points: 400,
    order: 4,
    isActive: true,
  },

  // ==================== SPECIAL BADGES ====================
  {
    id: 'target_crusher',
    name: 'Goal Achieved',
    description: 'First target completed',
    category: 'SPECIAL',
    tier: 'BRONZE',
    icon: '🏁',
    requirement: JSON.stringify({ type: 'TARGET_COMPLETED', value: 1 }),
    points: 50,
    order: 1,
    isActive: true,
  },
  {
    id: 'perfect_month',
    name: 'Flawless Month',
    description: '100% win rate in calendar month (min 20 trades)',
    category: 'SPECIAL',
    tier: 'PLATINUM',
    icon: '🎯',
    requirement: JSON.stringify({ type: 'PERFECT_MONTH', minTrades: 20 }),
    points: 500,
    order: 2,
    isActive: true,
  },
  {
    id: 'early_bird',
    name: 'Dawn Trader',
    description: '50 ASIA session trades',
    category: 'SPECIAL',
    tier: 'BRONZE',
    icon: '🌅',
    requirement: JSON.stringify({ type: 'SESSION_TRADES', sessionType: 'ASIA', value: 50 }),
    points: 40,
    order: 3,
    isActive: true,
  },
  {
    id: 'night_owl',
    name: 'Night Trader',
    description: '50 US session trades',
    category: 'SPECIAL',
    tier: 'BRONZE',
    icon: '🌃',
    requirement: JSON.stringify({ type: 'SESSION_TRADES', sessionType: 'US', value: 50 }),
    points: 40,
    order: 4,
    isActive: true,
  },
  {
    id: 'comeback_kid',
    name: 'Resilient',
    description: 'Profitable day after 3 losing days',
    category: 'SPECIAL',
    tier: 'GOLD',
    icon: '🔄',
    requirement: JSON.stringify({ type: 'COMEBACK', losingDays: 3 }),
    points: 100,
    order: 5,
    isActive: true,
  },
  {
    id: 'grind_master',
    name: 'Hard Worker',
    description: '50+ trades in single day',
    category: 'SPECIAL',
    tier: 'GOLD',
    icon: '💪',
    requirement: JSON.stringify({ type: 'MAX_TRADES_DAY', value: 50 }),
    points: 150,
    order: 6,
    isActive: true,
  },
  {
    id: 'early_adopter',
    name: 'Founding Member',
    description: 'Early platform user',
    category: 'SPECIAL',
    tier: 'PLATINUM',
    icon: '🎁',
    requirement: JSON.stringify({ type: 'EARLY_ADOPTER', registrationDate: '2026-02-01' }),
    points: 200,
    order: 7,
    isActive: true,
  },
];
